### ISSUE TITLE
Peer to Peer code review

### ISSUE THREAD

**Issue by jaimevillegas** [yosaddis/Awesome-Books-ES6#2]
Hi @yosaddis!

Your code looks awesome, it is well-commented and easy to read. We recommend you make the following changes: ♻️
- Try to deal with linter errors in `books.js`. We think that you can solve the linter errors that you have disabled 🚀
- Yoseph’s code contains enough comments for each method or function, which is a great practice. However, I believe the index.html would have been made much cleaner.

**Comment by yosaddis** [comment]
Thanks for the review guys. All issues are fixed.
